language: php

sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.3
        - php: 5.6
        - php: 7.0
          env: deps=low
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - if [[ $deps = low ]]; then composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable; fi
    - if [[ ! $deps ]]; then composer install --no-interaction --no-progress --ansi; fi

script: ./vendor/bin/phpunit

notifications:
    email: false
